#!/bin/bash

if [[ ${BASH_VERSINFO[0]} -gt 3 ]]; then
    shopt -s extglob
    shopt -s globstar
    shopt -s dotglob
fi

DOTFILES_PATH="${HOME}/Dotfiles"
PRIVATEFILES_PATH="${DOTFILES_PATH}/private"
# shellcheck disable=SC2034
PS1_PROMPTS_PATH="${DOTFILES_PATH}/ps1"
STARTUP_SEQUENCE="${DOTFILES_PATH}/startup-sequence"

# shellcheck source=./startup-sequence/env
source "${STARTUP_SEQUENCE}/env"

# shellcheck source=./startup-sequence/alias
source "${STARTUP_SEQUENCE}/alias"

# shellcheck source=./startup-sequence/colors
source "${STARTUP_SEQUENCE}/colors"

export DFL_LS_COLOR=1
export DFL_LESS_COLOR=1
export DFL_PS1_COLORS=1

# custom options for un-setting colors ----------------------------------------
if [[ -e "${DOTFILES_PATH}/options" ]]; then
    # shellcheck source=/dev/null
    source "${DOTFILES_PATH}/options"
fi

if [[ -n "${DFL_PS1_COLORS+x}" ]]; then
    # shellcheck source=/dev/null
    source "${STARTUP_SEQUENCE}/sample-ps1-colors"
fi
# -----------------------------------------------------------------------------

# shellcheck source=./startup-sequence/ps1-setup
source "${STARTUP_SEQUENCE}/ps1-setup"


# osx only
# -----------------------------------------------------------------------------
if [[ $(uname) == "Darwin" ]]; then
    # shellcheck source=/dev/null
    source "${STARTUP_SEQUENCE}/osx"
    export DFL_OS="OSX"
fi
# -----------------------------------------------------------------------------


# ubuntu only
# -----------------------------------------------------------------------------
if [[ $(command -v lsb_release) ]]; then
    # shellcheck disable=SC2143
    if [[ $(lsb_release -i | grep -i 'ubuntu') ]]; then
        export DFL_OS="UBUNTU"
        # shellcheck source=/dev/null
        source "${STARTUP_SEQUENCE}/ubuntu"
    fi
fi


# gentoo only
# -----------------------------------------------------------------------------
if [[ $(uname -r | awk -F - '{print $2}') == "gentoo" ]]; then
    export DFL_OS="GENTOO"
    # shellcheck source=/dev/null
    source "${STARTUP_SEQUENCE}/gentoo"
fi
# -----------------------------------------------------------------------------


export PS1="${PS1_BASIC}"


# load functions
# -----------------------------------------------------------------------------
for file in "${STARTUP_SEQUENCE}"/functions/*; do
    # shellcheck source=/dev/null
    source "${file}"
done
# -----------------------------------------------------------------------------


# bash-completions
# -----------------------------------------------------------------------------
for file in "${STARTUP_SEQUENCE}"/completions/*; do
    # shellcheck source=/dev/null
    source "${file}"
done
# -----------------------------------------------------------------------------


# check colors if enabled -----------------------------------------------------
if [[ -n ${DFL_LS_COLOR+x} ]]; then
    if [[ -n ${DFL_LS_COLORABLE+x} ]]; then
        # shellcheck source=./startup-sequence/ls-colors
        source "${STARTUP_SEQUENCE}/ls-colors"
    fi
fi

if [[ -n ${DFL_LESS_COLOR+x} ]]; then
    # shellcheck source=./startup-sequence/less-colors
    source "${STARTUP_SEQUENCE}/less-colors"
fi
# -----------------------------------------------------------------------------

# always last!
# load private files ----------------------------------------------------------
if [[ -n "$(\ls -A "${PRIVATEFILES_PATH}" 2>/dev/null)" ]]; then
    for file in "${PRIVATEFILES_PATH}"/*; do
        file_base_name=$(basename "${file}")
        if [[ "${file_base_name:0:1}" != "." ]]; then
            # shellcheck source=/dev/null
            source "${file}"
        fi
    done
fi
# -----------------------------------------------------------------------------
