#!/usr/bin/env bash

# this file is sourced by bashrc

# shellcheck disable=SC2154
export DFL_HORIZONTAL_LINE_PROMPT_COLOR="${gray}"                      # [------]
export DFL_BASH_VERSION_INFO_PROMPT_COLOR="${gray}"                    # [4.4.5(1)-release]
export DFL_MEMORY_PROMPT_COLOR="${green}${bold}"                       # [2.43G]

# vigo at noto.local in ~
export DFL_USER_HOSTNAME_USER_PROMPT_COLOR="${blue}"
export DFL_USER_HOSTNAME_HOSTNAME_PROMPT_COLOR="${red}"
export DFL_USER_HOSTNAME_CWD_PROMPT_COLOR="${white}"

# git/hg
export DFL_REVCONTROL_BRANCH_COLOR="${green}"                          # master
export DFL_REVCONTROL_AT_SIGN_COLOR="${white}"                         # @
export DFL_REVCONTROL_COMMIT_ID_COLOR="${underline}"                   # 4a449eb1d5e5
export DFL_REVCONTROL_UNTRACKED_COLOR="${red}"                         # □
export DFL_REVCONTROL_ADDED_COLOR="${yellow}${bold}"                   # ■
export DFL_REVCONTROL_MODIFIED_COLOR="${green}"                        # ◆
export DFL_REVCONTROL_RENAMED_COLOR="${yellow}"                        # ◇
export DFL_REVCONTROL_DELETED_COLOR="${blink}${magenta}"               # ◌
export DFL_REVCONTROL_TYPECHANGED_COLOR="${cyan}"                      # ❖
export DFL_REVCONTROL_OVERALL_COLOR="${white}"                         #
export DFL_REVCONTROL_VERTICAL_PIPE_COLOR="${gray}"                    # |
export DFL_REVCONTROL_GIT_BRANCH_AHEAD_COLOR="${reverse}${white}"      # →
export DFL_REVCONTROL_GIT_BRANCH_BEHIND_COLOR="${reverse}${white}"     # ←

# git
export DFL_REVCONTROL_GIT_SHOW_DIFF_SINCE_LAST_COMMIT_COLOR="${yellow}" # (69 minutes ago)
export DFL_REVCONTROL_GIT_SHOW_LATEST_TAG_COLOR="${green}"              # [v1.3.0]

# battery
# export DFL_BATTERY_ICON="\xE2\x8C\xA7" # for custom icon :)          # [⌧ 7:48]
export DFL_BATTERY_PROMPT_COLOR="${yellow}"                            # [3:47]

# ip list
export DFL_IPLIST_PROMPT_IFACE_COLOR="${gray}${bold}"                  # [en0:192.168.2.205,vboxnet0:192.168.33.1]
export DFL_IPLIST_PROMPT_IPADDR_COLOR="${gray}"

# database status and icons
export DFL_DB_MYSQL_PROMPT_COLOR="${red}${blink}"                      # [MySQL]
export DFL_DB_POSTGRESQL_PROMPT_COLOR="${red}${blink}"                 # [PG]
export DFL_DB_REDIS_PROMPT_COLOR="${red}${blink}"                      # [REDIS]
export DFL_DB_MONGODB_PROMPT_COLOR="${red}${blink}"                    # [MONGODB]
export DFL_DB_POSTGRESQL_DOCKER_ICON="\xF0\x9F\x9A\xA2"                # 🚢

# libs
export DFL_VIRTUALENV_PROMPT_COLOR="${red}${bold}"                     # [⚑ resume.bilgi.edu.tr]
export DFL_RBENV_PROMPT_COLOR="${yellow}"                              # [◆ 2.3.3]
export DFL_PYTHON_PROMPT_COLOR="${blue}"                               # [¶ 2.7.12]
export DFL_DJANGO_PROMPT_COLOR="${cyan}${underline}"                   # [❡ 1.10.1]
export DFL_NODE_PROMPT_COLOR="${yellow}"                               # [⎆ v16.0.0]
export DFL_NPM_PROMPT_COLOR="${gray}"                                  # [▢ 6.4.1]
export DFL_YARN_PROMPT_COLOR="${red}"                                  # [▣ 6.4.1]
export DFL_PGVM_PROMPT_COLOR="${magenta}"                              # [▥ 9.3.4]
export DFL_GO_PROMPT_COLOR="${white}"                                  # [⍟ 1.16.3]
