#!/usr/bin/env bash

function gz_analyse() {
    if [[ $1 ]]; then
        echo "orig size (bytes): "
        wc -c "${1}"
        echo "gzipped size (bytes): "
        gzip -c "${1}" | wc -c
    else
        echo "usage: gz_analyse file"
    fi
}
