#!/usr/bin/env bash

mkdir_now(){
    now=$(date +"%Y-%m-%d-%H%M%S")
    mkdir "${now}" || return 1 
}

mkdir_now_short(){
    now=$(date +"%Y-%m-%d")
    mkdir "${now}" || return 1 
}

mkdir_now_cd(){
    now=$(date +"%Y-%m-%d-%H%M%S")
    mkdir "${now}"
    cd "${now}" || return 1 
}

mkdir_now_short_cd(){
    now=$(date +"%Y-%m-%d")
    mkdir "${now}"
    cd "${now}" || return 1 
}