#!/usr/bin/env bash

function webserver() {
    if [[ $1 == "-h" || $1 == "--help" ]]; then
        echo "Simple, http static html server via Python."
        echo "Usage:"
        echo -e "\twebserver PORT"
        echo -e "\twebserver # default port is 8000"
        echo
        echo "-h, --help: help"
        echo
        return 0
    fi
    local port="${1:-8000}"
    
    python_major_version=$(python -c 'import sys;print(sys.version_info.major)')
    if [[ "${python_major_version}" == "2" ]]; then
        python -m SimpleHTTPServer "${port}"
    else
        python -m http.server "${port}"
    fi
}

_server()
{
    local cur opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts="8000 -h --help"
    if [[ ${cur} == * ]] ; then
        while IFS='' read -r line; do COMPREPLY+=("$line"); done < <(compgen -W "${opts}" -- "${cur}")
        return 0
    fi
}
complete -F _server webserver -o nospace
