#!/usr/bin/env bash

if [[ $(basename "${SHELL}") == 'bash' ]]; then
    DFL_BASH_VERSION_INFO_PROMPT_ICON="${DFL_BASH_VERSION_INFO_PROMPT_ICON:-⏍ }"
    bash_version_info="${DFL_BASH_VERSION_INFO_PROMPT_ICON}${BASH_VERSION}"

    if [[ $DFL_BASH_VERSION_INFO_PROMPT_COLOR ]]; then
        bash_version_info="${DFL_BASH_VERSION_INFO_PROMPT_COLOR}${bash_version_info}${COLOR_OFF}"
    fi
    printf "[%b]" "${bash_version_info}"
fi
