#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

# emoji battery: \xF0\x9F\x94\x8B 🔋

if [[ $(uname) == "Darwin" ]]; then
    power_data=$(pmset -g batt)
    result=""
    if [[ ! "${power_data}" == *"AC Power"* ]]; then
        
        battery_time_remaining=$(pmset -g batt | grep -E "([0-9]+\%).*" -o --colour=auto | cut -f3 -d';')
        if [[ "${battery_time_remaining}" == *"no estimate"* ]]; then
            result="??"
        else
            result=$(pmset -g batt | grep -E "([0-9]+\%).*" -o --colour=auto | cut -f3 -d';' | cut -f2 -d' ')
        fi
        DFL_BATTERY_PROMPT_ICON="${DFL_BATTERY_PROMPT_ICON:-\xE2\x8C\xA7 }"

        out="${DFL_BATTERY_PROMPT_ICON}${result}"

        if [[ "${DFL_BATTERY_SHOW_PERCENT_REMAINING}" ]]; then
            battery_percent=$(pmset -g batt | grep -E "([0-9]+\%).*" -o --colour=auto | cut -f1 -d';')
            out="${out} ${battery_percent}"
        fi

        if [[ "${DFL_BATTERY_PROMPT_COLOR}" ]]; then
            out="${DFL_BATTERY_PROMPT_COLOR}${out}${COLOR_OFF}"
        fi

        printf "[%b]" "${out}"
    fi
fi
