#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

# emoji battery: \xF0\x9F\x94\x8B 🔋

if [[ $(uname) == "Darwin" ]]; then
    power_data=$(pmset -g batt)
    result=""
    if [[ ! $power_data == *"AC Power"* ]]; then
        battery_percent=$(pmset -g batt | egrep "([0-9]+\%).*" -o --colour=auto | cut -f1 -d';')
        battery_time_remaining=$(pmset -g batt | egrep "([0-9]+\%).*" -o --colour=auto | cut -f3 -d';')
        if [[ $battery_time_remaining == *"no estimate"* ]]; then
            result="??"
        else
            result=$(pmset -g batt | egrep "([0-9]+\%).*" -o --colour=auto | cut -f3 -d';' | cut -f2 -d' ')
        fi
        
        out="${result}"
        if [[ $DFL_BATTERY_ICON ]]; then
            out="${DFL_BATTERY_ICON} ${out}"
        fi
        if [[ $DFL_BATTERY_PROMPT_COLOR ]]; then
            out="${DFL_BATTERY_PROMPT_COLOR}${out}${COLOR_OFF}"
        fi
        printf "[${out}]"
    fi
fi
