#!/usr/bin/env bash

set -e

get_mysql_status() {
    if [[ $(command -v mysql.server) ]]; then
        mysql_status=$(mysql.server status)
        regex="running \(([0-9]+)\)"
        if [[ "${mysql_status}" =~ $regex ]]; then
            mysql_pid=${BASH_REMATCH[1]}
            out="MySQL"
            if [[ ${DFL_DB_MYSQL_PROMPT_COLOR} ]]; then
                out="${DFL_DB_MYSQL_PROMPT_COLOR}${out}${COLOR_OFF}"
            fi
            printf "[${out}]"
        fi
    fi
    
}

get_postgresql_status() {
    postgresql_status=""

    if [[ $(command -v pg_ctl) ]] && [[ ! -z "${PGDATA}" ]]; then
        postgresql_local_status=$(pg_ctl status -D "${PGDATA}")
        if [[ ! -z "${postgresql_local_status}" ]]; then
            postgresql_status="${postgresql_local_status}"
            out="PG"
        fi
    fi
    
    if [[ $(command -v docker) ]]; then
        postgresql_docker_status=$(docker exec -it --user postgres ${DFL_DOCKER_PG_CONTAINER_NAME} pg_ctl status 2> /dev/null)
        if [[ ! -z "${postgresql_docker_status}" ]]; then
            postgresql_status="${postgresql_docker_status}"
            out="PG"
            if [[ "${DFL_DB_POSTGRESQL_DOCKER_ICON}" ]]; then
                out="${out} ${DFL_DB_POSTGRESQL_DOCKER_ICON}"
            fi
        fi
    fi
    
    if [[ ! -z "${postgresql_status}" ]]; then
        regex="running \(PID: ([0-9]+)\)"
        if [[ ${postgresql_status} =~ $regex ]]; then
            postgresql_pid=${BASH_REMATCH[1]}
            
            if [[ "${DFL_DB_POSTGRESQL_PROMPT_COLOR}" ]]; then
                out="${DFL_DB_POSTGRESQL_PROMPT_COLOR}${out}${COLOR_OFF}"
            fi
            
            if [[ ! -z "${DATABASE_URL}" ]]; then
                out="${out} $(basename ${DATABASE_URL})"
            fi
            
            printf "[${out}]"
        fi
    fi
}

get_redis_status() {
    if [[ $(command -v redis-cli) ]]; then
        redis_ping=$(redis-cli ping > /dev/null 2>&1)
        if [[ $? == 0 ]]; then
            out="REDIS"
            if [[ "${DFL_DB_REDIS_PROMPT_COLOR}" ]]; then
                out="${DFL_DB_REDIS_PROMPT_COLOR}${out}${COLOR_OFF}"
            fi
            echo "[${out}]"
        fi
    fi
}

get_mongodb_status() {
    if [[ $(command -v mongod) ]]; then
        mongodb_pid=$(pgrep mongod > /dev/null 2>&1)
        if [[ $? == 0 ]]; then
            out="MONGODB"
            if [[ "${DFL_DB_MONGODB_PROMPT_COLOR}" ]]; then
                out="${DFL_DB_MONGODB_PROMPT_COLOR}${out}${COLOR_OFF}"
            fi
            echo "[${out}]"
        fi
    fi
}

if [[ $(uname) == "Darwin" ]]; then
    mysql_status=$(get_mysql_status)
    postgresql_status=$(get_postgresql_status)
    redis_status=$(get_redis_status)
    mongodb_status=$(get_mongodb_status)
    echo "${mysql_status}${postgresql_status}${redis_status}${mongodb_status}"
fi
