#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx


if [[ $(uname) == "Darwin" ]]; then
    installed_memory=$(sysctl -n hw.memsize)
    installed_memory_in_gb=$(bc <<< "scale=2; $installed_memory/1024/1024/1000")
    page_types=("wired down" "active" "inactive")
    all_consumed=0
    for page_type in "${page_types[@]}"; do
        consumed=$(vm_stat | grep "Pages ${page_type}:" | awk -F: '{print $2}' | tr -d '[[:space:]]' | grep -E "[[:digit:]]*" -ho)
        consumed_gb=$(bc <<< "scale=2; ($consumed*4096)/1024/1024/1000")
        all_consumed=$(bc <<< "scale=2; $all_consumed+$consumed_gb")
    done
    what_is_remaining=$(bc <<< "scale=2; $installed_memory_in_gb-$all_consumed")
    result=$(printf "%.2fG" "${what_is_remaining}")
    if [[ $DFL_MEMORY_PROMPT_COLOR ]]; then
        result="${DFL_MEMORY_PROMPT_COLOR}${result}${COLOR_OFF}"
    fi
    printf "[${result}]"
fi