#!/usr/bin/env bash

if [[ $(command -v python) ]]; then
    DFL_PYTHON_PROMPT_ICON="${DFL_PYTHON_PROMPT_ICON:-¶ }"
    DFL_PYTHON_DJANGO_PROMPT_ICON="${DFL_PYTHON_DJANGO_PROMPT_ICON:-❡ }"

    python_version=$($(command -v python) --version 2>&1 | cut -d' ' -f2)

    if [[ $(command -v pyenv) ]]; then
        pyenv_version=$($(command -v pyenv) version-name)
        if [[ ${pyenv_version} != "system" ]]; then
            python_version="${DFL_PYTHON_PROMPT_ICON}${pyenv_version}"
        fi
    fi
    if [[ ${DFL_PYTHON_PROMPT_COLOR} ]]; then
        python_version="${DFL_PYTHON_PROMPT_COLOR}${DFL_PROMPT_BRACKET_OPEN}${python_version}${DFL_PROMPT_BRACKET_CLOSE}${COLOR_OFF}"
    fi
    printf "%b" "${python_version}"


    django_version=""
    if [[ $(command -v django-admin) ]]; then
        django_check_version="$(django-admin --version 2>&1)"
        err_code="${?}"
        
        if [[ $err_code == "0" ]]; then
            django_version="${django_check_version}"
        fi
    fi
    if [[ -n "${django_version}" ]]; then
        django_version="${DFL_PYTHON_DJANGO_PROMPT_ICON}${django_version}"
        if [[ ${DFL_DJANGO_PROMPT_COLOR} ]]; then
            django_version="${DFL_DJANGO_PROMPT_COLOR}${DFL_PROMPT_BRACKET_OPEN}${django_version}${DFL_PROMPT_BRACKET_CLOSE}${COLOR_OFF}"
        fi
        printf "%b" "${django_version}"
    fi
fi
