#!/usr/bin/env bash

if [[ $(command -v ruby) ]]; then
    DFL_RBENV_PROMPT_ICON="${DFL_RBENV_PROMPT_ICON:-◆ }"
    ruby_version=$(ruby -e 'puts RUBY_VERSION' 2>&1)
    if [[ $(command -v rbenv) ]]; then
        rbenv_version=$(rbenv version-name)
        if [[ ${rbenv_version} != "system" ]]; then
            ruby_version="${DFL_RBENV_PROMPT_ICON}${rbenv_version}"
        fi
    fi

    if [[ ${DFL_RBENV_PROMPT_COLOR} ]]; then
        ruby_version="${DFL_RBENV_PROMPT_COLOR}${DFL_PROMPT_BRACKET_OPEN}${ruby_version}${DFL_PROMPT_BRACKET_CLOSE}${COLOR_OFF}"
    fi

    printf "%b" "${ruby_version}"
fi
