name: Shellcheck

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run shellchecker
        run: |
          shellcheck ps1/*
          shellcheck --shell=bash startup-sequence/functions/*
