name: Shellcheck

on:
  push:
    branches: [ main, fix/* ]
  pull_request:
    branches: [ main, fix/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run shellchecker
        run: |
          shellcheck --shell=bash ps1/*
          shellcheck --shell=bash startup-sequence/functions/*
          shellcheck --shell=bash startup-sequence/osx
          shellcheck --shell=bash startup-sequence/ps1-setup
          shellcheck --shell=bash startup-sequence/sample-ps1-colors
